// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace iBloodPressure {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("AddBloodPressureViewController")]
	public partial class AddBloodPressureViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextField __mt_diastolic;
		
		private MonoTouch.UIKit.UITextField __mt_pulsePerMin;
		
		private MonoTouch.UIKit.UITextField __mt_systolic;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("ResignToKeboard:")]
		partial void ResignToKeboard (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("diastolic")]
		private MonoTouch.UIKit.UITextField diastolic {
			get {
				this.__mt_diastolic = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("diastolic")));
				return this.__mt_diastolic;
			}
			set {
				this.__mt_diastolic = value;
				this.SetNativeField("diastolic", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("pulsePerMin")]
		private MonoTouch.UIKit.UITextField pulsePerMin {
			get {
				this.__mt_pulsePerMin = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("pulsePerMin")));
				return this.__mt_pulsePerMin;
			}
			set {
				this.__mt_pulsePerMin = value;
				this.SetNativeField("pulsePerMin", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("systolic")]
		private MonoTouch.UIKit.UITextField systolic {
			get {
				this.__mt_systolic = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("systolic")));
				return this.__mt_systolic;
			}
			set {
				this.__mt_systolic = value;
				this.SetNativeField("systolic", value);
			}
		}
	}
}
